plugins:
  - jekyll
  - jekyll-paginate
  - jekyll-sitemap
  - ruby

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]